name: Dev CI

# Event to trigger this workflow.
on:
  push:
    branches: ['*']
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]

jobs:
  all-cli-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.x']
    steps:
      - name: Check the github repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Installing node.js ${{ matrix.node-version }} on the container
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Run lint
        run: npm run lint
      - name: Run format
        run: npm run format
        # For test-first development approach
      # if: ${{github.actor != github.repository_owner}}
      - name: Run test
        run: npm run test
